import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Copy sql-wasm.wasm to build output
function copyWasmPlugin() {
  return {
    name: "copy-wasm",
    setup(build) {
      build.onEnd(() => {
        const wasmSrc = join("node_modules", "sql.js-fts5", "dist", "sql-wasm.wasm");
        const wasmDest = join(dirname(build.initialOptions.outfile), "sql-wasm.wasm");
        if (existsSync(wasmSrc)) {
          mkdirSync(dirname(wasmDest), { recursive: true });
          copyFileSync(wasmSrc, wasmDest);
          console.log("Copied sql-wasm.wasm");
        }
      });
    },
  };
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copyWasmPlugin()],
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
